name: CI without cache

on: workflow_dispatch

jobs:
  ci:
    name: Running CI
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
          path: |
            **/target

      - name: install packages
        run: mvn clean package
